/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.fraudpreventionv2.models.AccountTakeoverCustomerAccount
import com.expediagroup.sdk.fraudpreventionv2.models.AccountTakeoverDeviceDetails
import com.expediagroup.sdk.fraudpreventionv2.models.AccountTakeoverSiteInfo
import com.expediagroup.sdk.fraudpreventionv2.models.AccountTakeoverTransactionDetails
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull

/**
 * Information for an account transaction.
 * @param siteInfo
 * @param deviceDetails
 * @param customerAccount
 * @param transactionDetails
 */
data class AccountTransaction(
    @JsonProperty("site_info")
    @field:NotNull
    @field:Valid
    val siteInfo: AccountTakeoverSiteInfo,
    @JsonProperty("device_details")
    @field:NotNull
    @field:Valid
    val deviceDetails: AccountTakeoverDeviceDetails,
    @JsonProperty("customer_account")
    @field:NotNull
    @field:Valid
    val customerAccount: AccountTakeoverCustomerAccount,
    @JsonProperty("transaction_details")
    @field:NotNull
    @field:Valid
    val transactionDetails: AccountTakeoverTransactionDetails
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var siteInfo: AccountTakeoverSiteInfo? = null,
        private var deviceDetails: AccountTakeoverDeviceDetails? = null,
        private var customerAccount: AccountTakeoverCustomerAccount? = null,
        private var transactionDetails: AccountTakeoverTransactionDetails? = null
    ) {
        fun siteInfo(siteInfo: AccountTakeoverSiteInfo) = apply { this.siteInfo = siteInfo }

        fun deviceDetails(deviceDetails: AccountTakeoverDeviceDetails) = apply { this.deviceDetails = deviceDetails }

        fun customerAccount(customerAccount: AccountTakeoverCustomerAccount) = apply { this.customerAccount = customerAccount }

        fun transactionDetails(transactionDetails: AccountTakeoverTransactionDetails) = apply { this.transactionDetails = transactionDetails }

        fun build(): AccountTransaction {
            val instance =
                AccountTransaction(
                    siteInfo = siteInfo!!,
                    deviceDetails = deviceDetails!!,
                    customerAccount = customerAccount!!,
                    transactionDetails = transactionDetails!!
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: AccountTransaction) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            siteInfo = siteInfo!!,
            deviceDetails = deviceDetails!!,
            customerAccount = customerAccount!!,
            transactionDetails = transactionDetails!!
        )
}
