/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern

/**
 *
 * @param `value` The amount required in payment for the product/order in local currency (including any taxes and fees).
 * @param currencyCode The ISO  alpha-3 country code for the amount currency.
 */
data class Amount(
    // The amount required in payment for the product/order in local currency (including any taxes and fees).
    @JsonProperty("value")
    val `value`: kotlin.Double,
    // The ISO  alpha-3 country code for the amount currency.
    @JsonProperty("currency_code")
    @field:Pattern(regexp = "^[A-Z]{3}$")
    @field:Length(max = 3)
    @field:NotNull
    @field:Valid
    val currencyCode: kotlin.String
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var `value`: kotlin.Double? = null,
        private var currencyCode: kotlin.String? = null
    ) {
        fun `value`(`value`: kotlin.Double) = apply { this.`value` = `value` }

        fun currencyCode(currencyCode: kotlin.String) = apply { this.currencyCode = currencyCode }

        fun build(): Amount {
            val instance =
                Amount(
                    `value` = `value`!!,
                    currencyCode = currencyCode!!
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: Amount) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            `value` = `value`!!,
            currencyCode = currencyCode!!
        )
}
