/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern

/**
 *
 * @param ipAddress IP address of the device used for booking.
 * @param source Source of the device_box. Default value is `TrustWidget`.
 * @param deviceBox Device related information retrieved from TrustWidget.
 */
data class DeviceDetails(
    // IP address of the device used for booking.
    @JsonProperty("ip_address")
    @field:Pattern(regexp = "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$|^(?:[A-F0-9]{1,4}:){7}[A-F0-9]{1,4}$")
    @field:NotNull
    @field:Valid
    val ipAddress: kotlin.String,
    // Source of the device_box. Default value is `TrustWidget`.
    @JsonProperty("source")
    @field:Length(max = 50)
    @field:Valid
    val source: kotlin.String? = null,
    // Device related information retrieved from TrustWidget.
    @JsonProperty("device_box")
    @field:Valid
    val deviceBox: kotlin.String? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var ipAddress: kotlin.String? = null,
        private var source: kotlin.String? = null,
        private var deviceBox: kotlin.String? = null
    ) {
        fun ipAddress(ipAddress: kotlin.String) = apply { this.ipAddress = ipAddress }

        fun source(source: kotlin.String?) = apply { this.source = source }

        fun deviceBox(deviceBox: kotlin.String?) = apply { this.deviceBox = deviceBox }

        fun build(): DeviceDetails {
            val instance =
                DeviceDetails(
                    ipAddress = ipAddress!!,
                    source = source,
                    deviceBox = deviceBox
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: DeviceDetails) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            ipAddress = ipAddress!!,
            source = source,
            deviceBox = deviceBox
        )
}
