/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.fraudpreventionv2.models.Telephone
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull
import javax.validation.constraints.Size

/**
 *
 * @param accountNumber Cleartext (unencrypted) DirectDebit bank account number associated with the payment instrument.
 * @param telephones Telephone(s) associated with direct debit payment provider.
 * @param routingNumber A code that identifies the financial institution for a specific bank account. `routing_number` is required if given `INTER_COMPANY` or `ELV` as `brand`.
 * @param mandateType The `mandate_type` is required if given `brand` as `SEPA_ELV` under `DirectDebit`.  It is used for the wire transfer or direct debit transaction whose `routing_number` could not be provided or not supported.   Allows values:  - `ONE_OFF`  - `RECURRING`
 */
data class DirectDebitAllOf(
    // Cleartext (unencrypted) DirectDebit bank account number associated with the payment instrument.
    @JsonProperty("account_number")
    @field:Length(max = 100)
    @field:NotNull
    @field:Valid
    val accountNumber: kotlin.String,
    // Telephone(s) associated with direct debit payment provider.
    @JsonProperty("telephones")
    @field:Size(min = 1, max = 20)
    @field:NotNull
    @field:Valid
    val telephones: kotlin.collections
        .List<
            Telephone
        >,
    // A code that identifies the financial institution for a specific bank account. `routing_number` is required if given `INTER_COMPANY` or `ELV` as `brand`.
    @JsonProperty("routing_number")
    @field:Length(max = 15)
    @field:Valid
    val routingNumber: kotlin.String? = null,
    // The `mandate_type` is required if given `brand` as `SEPA_ELV` under `DirectDebit`.  It is used for the wire transfer or direct debit transaction whose `routing_number` could not be provided or not supported.   Allows values:  - `ONE_OFF`  - `RECURRING`
    @JsonProperty("mandate_type")
    val mandateType: DirectDebitAllOf.MandateType? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var accountNumber: kotlin.String? = null,
        private var telephones: kotlin.collections.List<Telephone>? = null,
        private var routingNumber: kotlin.String? = null,
        private var mandateType: DirectDebitAllOf.MandateType? = null
    ) {
        fun accountNumber(accountNumber: kotlin.String) = apply { this.accountNumber = accountNumber }

        fun telephones(telephones: kotlin.collections.List<Telephone>) = apply { this.telephones = telephones }

        fun routingNumber(routingNumber: kotlin.String?) = apply { this.routingNumber = routingNumber }

        fun mandateType(mandateType: DirectDebitAllOf.MandateType?) = apply { this.mandateType = mandateType }

        fun build(): DirectDebitAllOf {
            val instance =
                DirectDebitAllOf(
                    accountNumber = accountNumber!!,
                    telephones = telephones!!,
                    routingNumber = routingNumber,
                    mandateType = mandateType
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: DirectDebitAllOf) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            accountNumber = accountNumber!!,
            telephones = telephones!!,
            routingNumber = routingNumber,
            mandateType = mandateType
        )

    /**
     * The `mandate_type` is required if given `brand` as `SEPA_ELV` under `DirectDebit`.  It is used for the wire transfer or direct debit transaction whose `routing_number` could not be provided or not supported.   Allows values:  - `ONE_OFF`  - `RECURRING`
     * Values: ONE_OFF,RECURRING
     */
    enum class MandateType(val value: kotlin.String) {
        @JsonProperty("ONE_OFF")
        ONE_OFF("ONE_OFF"),

        @JsonProperty("RECURRING")
        RECURRING("RECURRING")
    }
}
