/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.fraudpreventionv2.models.Amount
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull

/**
 * Data that describes issued refund that should be updated.
 * @param refundIssuedDateTime Date and time when the 3rd party payment processor confirmed that a previously submitted payment refund has issued at the participating financial institutions.
 * @param refundIssuedAmount
 */
data class IssuedRefundUpdateDetails(
    // Date and time when the 3rd party payment processor confirmed that a previously submitted payment refund has issued at the participating financial institutions.
    @JsonProperty("refund_issued_date_time")
    val refundIssuedDateTime: java.time.OffsetDateTime,
    @JsonProperty("refund_issued_amount")
    @field:NotNull
    @field:Valid
    val refundIssuedAmount: Amount
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var refundIssuedDateTime: java.time.OffsetDateTime? = null,
        private var refundIssuedAmount: Amount? = null
    ) {
        fun refundIssuedDateTime(refundIssuedDateTime: java.time.OffsetDateTime) = apply { this.refundIssuedDateTime = refundIssuedDateTime }

        fun refundIssuedAmount(refundIssuedAmount: Amount) = apply { this.refundIssuedAmount = refundIssuedAmount }

        fun build(): IssuedRefundUpdateDetails {
            val instance =
                IssuedRefundUpdateDetails(
                    refundIssuedDateTime = refundIssuedDateTime!!,
                    refundIssuedAmount = refundIssuedAmount!!
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: IssuedRefundUpdateDetails) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            refundIssuedDateTime = refundIssuedDateTime!!,
            refundIssuedAmount = refundIssuedAmount!!
        )
}
