/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.fraudpreventionv2.models.AccountUpdateRequest
import com.expediagroup.sdk.fraudpreventionv2.models.MultiFactorAuthenticationAttempt
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull
import javax.validation.constraints.Size

/**
 * Information specific to a user's response to a Multi-Factor Authentication initiated by the Partner's system as a result of a fraud recommendation.
 * @param multiFactorAuthenticationAttempts
 */
data class MultiFactorAuthenticationUpdate(
    // The `risk_id` provided by Expedia's Fraud Prevention Service in the `AccountScreenResponse`.
    @JsonProperty("risk_id")
    @field:Length(max = 200)
    @field:NotNull
    @field:Valid
    override val riskId: kotlin.String,
    @JsonProperty("multi_factor_authentication_attempts")
    @field:Size(min = 1, max = 20)
    @field:NotNull
    @field:Valid
    val multiFactorAuthenticationAttempts: kotlin.collections
        .List<
            MultiFactorAuthenticationAttempt
        >
) : AccountUpdateRequest {
    @JsonProperty("type")
    override val type: AccountUpdateRequest.Type = AccountUpdateRequest.Type.MULTI_FACTOR_AUTHENTICATION_UPDATE

    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var riskId: kotlin.String? = null,
        private var multiFactorAuthenticationAttempts: kotlin.collections.List<MultiFactorAuthenticationAttempt>? = null
    ) {
        fun riskId(riskId: kotlin.String) = apply { this.riskId = riskId }

        fun multiFactorAuthenticationAttempts(multiFactorAuthenticationAttempts: kotlin.collections.List<MultiFactorAuthenticationAttempt>) =
            apply {
                this.multiFactorAuthenticationAttempts =
                    multiFactorAuthenticationAttempts
            }

        fun build(): MultiFactorAuthenticationUpdate {
            val instance =
                MultiFactorAuthenticationUpdate(
                    riskId = riskId!!,
                    multiFactorAuthenticationAttempts = multiFactorAuthenticationAttempts!!
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: MultiFactorAuthenticationUpdate) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            riskId = riskId!!,
            multiFactorAuthenticationAttempts = multiFactorAuthenticationAttempts!!
        )
}
