/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.fraudpreventionv2.models.Address
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull

/**
 *
 * @param name The popularly known name or title by which the railway station is identified.
 * @param stationCode The unique identifier or code assigned to an individual rail station or a pseudo-station representing all the stations within a specific city, from which rail travel originates.
 * @param address
 * @param type This attribute provides information about the specific classification assigned to the rail station. It helps differentiate between different types of stations, such as major stations (STATION) or stations located within a city (city).
 * @param timezone The timezone associated with the location of the station, specifying the local time offset from Coordinated Universal Time (UTC).
 */
data class RailwayStationDetails(
    // The popularly known name or title by which the railway station is identified.
    @JsonProperty("name")
    @field:Length(max = 200)
    @field:NotNull
    @field:Valid
    val name: kotlin.String,
    // The unique identifier or code assigned to an individual rail station or a pseudo-station representing all the stations within a specific city, from which rail travel originates.
    @JsonProperty("station_code")
    @field:Length(max = 200)
    @field:NotNull
    @field:Valid
    val stationCode: kotlin.String,
    @JsonProperty("address")
    @field:NotNull
    @field:Valid
    val address: Address,
    // This attribute provides information about the specific classification assigned to the rail station. It helps differentiate between different types of stations, such as major stations (STATION) or stations located within a city (city).
    @JsonProperty("type")
    val type: RailwayStationDetails.Type? = null,
    // The timezone associated with the location of the station, specifying the local time offset from Coordinated Universal Time (UTC).
    @JsonProperty("timezone")
    @field:Length(max = 200)
    @field:Valid
    val timezone: kotlin.String? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var name: kotlin.String? = null,
        private var stationCode: kotlin.String? = null,
        private var address: Address? = null,
        private var type: RailwayStationDetails.Type? = null,
        private var timezone: kotlin.String? = null
    ) {
        fun name(name: kotlin.String) = apply { this.name = name }

        fun stationCode(stationCode: kotlin.String) = apply { this.stationCode = stationCode }

        fun address(address: Address) = apply { this.address = address }

        fun type(type: RailwayStationDetails.Type?) = apply { this.type = type }

        fun timezone(timezone: kotlin.String?) = apply { this.timezone = timezone }

        fun build(): RailwayStationDetails {
            val instance =
                RailwayStationDetails(
                    name = name!!,
                    stationCode = stationCode!!,
                    address = address!!,
                    type = type,
                    timezone = timezone
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: RailwayStationDetails) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            name = name!!,
            stationCode = stationCode!!,
            address = address!!,
            type = type,
            timezone = timezone
        )

    /**
     * This attribute provides information about the specific classification assigned to the rail station. It helps differentiate between different types of stations, such as major stations (STATION) or stations located within a city (city).
     * Values: STATION,CITY
     */
    enum class Type(val value: kotlin.String) {
        @JsonProperty("STATION")
        STATION("STATION"),

        @JsonProperty("CITY")
        CITY("CITY")
    }
}
