/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern

/**
 *
 * @param countryCode The alpha-3 ISO code that represents a country name.
 * @param agentAssisted Identifies if an agent assisted in booking travel for the customer. `False` if the order was directly booked by customer.
 */
data class SiteInfo(
    // The alpha-3 ISO code that represents a country name.
    @JsonProperty("country_code")
    @field:Pattern(regexp = "^[A-Z]{3}$")
    @field:NotNull
    @field:Valid
    val countryCode: kotlin.String,
    // Identifies if an agent assisted in booking travel for the customer. `False` if the order was directly booked by customer.
    @JsonProperty("agent_assisted")
    @field:NotNull
    @field:Valid
    val agentAssisted: kotlin.Boolean
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var countryCode: kotlin.String? = null,
        private var agentAssisted: kotlin.Boolean? = null
    ) {
        fun countryCode(countryCode: kotlin.String) = apply { this.countryCode = countryCode }

        fun agentAssisted(agentAssisted: kotlin.Boolean) = apply { this.agentAssisted = agentAssisted }

        fun build(): SiteInfo {
            val instance =
                SiteInfo(
                    countryCode = countryCode!!,
                    agentAssisted = agentAssisted!!
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: SiteInfo) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            countryCode = countryCode!!,
            agentAssisted = agentAssisted!!
        )
}
