/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.fraudpreventionv2.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.fraudpreventionv2.models.ThirdPartyProviderDetails
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull

/**
 *
 * @param providerDetails
 * @param paymentId Unique payment id assigned by the third party payment provider.
 */
data class ThirdPartyProviderAllOf(
    @JsonProperty("provider_details")
    @field:NotNull
    @field:Valid
    val providerDetails: ThirdPartyProviderDetails,
    // Unique payment id assigned by the third party payment provider.
    @JsonProperty("payment_id")
    @field:Length(max = 200)
    @field:NotNull
    @field:Valid
    val paymentId: kotlin.String
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var providerDetails: ThirdPartyProviderDetails? = null,
        private var paymentId: kotlin.String? = null
    ) {
        fun providerDetails(providerDetails: ThirdPartyProviderDetails) = apply { this.providerDetails = providerDetails }

        fun paymentId(paymentId: kotlin.String) = apply { this.paymentId = paymentId }

        fun build(): ThirdPartyProviderAllOf {
            val instance =
                ThirdPartyProviderAllOf(
                    providerDetails = providerDetails!!,
                    paymentId = paymentId!!
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: ThirdPartyProviderAllOf) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            providerDetails = providerDetails!!,
            paymentId = paymentId!!
        )
}
