name: Generate and Publish SDK Sources

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          SDK Version.
          E.g., 1.0.0, 1.0.1, 1.0.0-SNAPSHOT, etc.
        required: true
        type: string
      sdk_repo_ref:
        description: |
          Branch or tag to checkout on the `expediagroup-java-sdk` repository.
        type: string
        default: 'legacy'

jobs:
  generate-and-publish-sources:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-full-workflow.yaml@legacy
    secrets: inherit
    with:
      name: fraudPreventionV2
      ref: ${{ github.head_ref || github.ref_name }}
      repository: 'ExpediaGroup/fraud-prevention-java-sdk'
      version: ${{ inputs.version }}
      transformations: '--operationIdsToTags'
      sdk_repo_ref: ${{ inputs.sdk_repo_ref }}
